# Cấu hình ứng dụng Spring Boot
spring.application.name=live-football
# Cấu hình server (cổng và context path)
# server.port=8080

spring.devtools.add-properties=false

# Cấu hình logging
logging.level.web=DEBUG
logging.level.org.springframework.web=INFO
logging.level.com.myapp=INFO
logging.file.name=logs/application.log
# logging.level.org.hibernate.SQL=DEBUG
# logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
# logging.level.org.springframework.transaction=TRACE

# Cấu hình kết nối MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/db_bugiotv
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=db_bugiotv
spring.datasource.password=db-bugiotv@9810
# spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Cấu hình pool kết nối
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.idle-timeout=30000 
spring.datasource.hikari.connection-timeout=30000


# Cấu hình JPA (Java Persistence API)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=true
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect


# Cấu hình cache (nếu cần)
# spring.cache.type=simple

# Cấu hình session
# server.servlet.session.timeout=30m

# Cấu hình môi trường sản xuất
# spring.profiles.active=prod
